-- -=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=- --
--     Code generated by VGen by Christian Manuel    --
-- -=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=- --
library ieee;
use ieee.std_logic_1164.all;

Entity clk_Rst is
  generic(
    -- comment here
    clk_prd : integer -- comment
    -- comment
  );
  port(
    clk : out std_logic;
    input_one : in std_logic;
    input_two : in std_logic;
    rst : out std_logic;
    custom_signal : in t_tyasdpe
  );
end entity clk_Rst;

architecture clk_rst_arch of clk_rst is


begin

end architecture;
