-- -=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=- --
--     Code generated by VGen by Christian Manuel    --
-- -=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=- --
library ieee;
use ieee.std_logic_1164.all;

entity counter is
  port(
    clk : in std_logic;
    rst_n : in std_logic;
    count : out std_logic_vector(3 downto 0)
  );
end entity counter;

architecture counter_arch of counter is


begin

end architecture;
