-- -=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=- --
--     Code generated by VGen by Christian Manuel    --
-- -=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=- --
library ieee;
use ieee.std_logic_1164.all;

entity counter is
  port(
    clk : out std_logic;
    rst_n : out std_logic
  );
end entity counter;

architecture counter_arch of counter is
begin

      process
      begin
            clk <= '0';
            wait for 5 ns;
            clk <= '1';
            wait for 5 ns;
      end process;

      process
      begin
            rst_n <= '0';
            wait for 2 ns;
            rst_n <= '1';
            wait;
      end process;

end architecture;
