-- -=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=- --
--     Code generated by VGen by Christian Manuel    --
-- -=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=- --
library ieee;
use ieee.std_logic_1164.all;

entity tb_top is
end entity tb_top;

architecture tb_top_arch of tb_top is

  component clk_Rst is
  generic(
    clk_prd : integer
  );
  port(
    clk : out std_logic;
    input_one : in std_logic;
    input_two : in std_logic;
    rst : out std_logic;
    custom_signal : in std_logic
  );
  end component clk_Rst;

  component clock is
  port(
    clk : in std_logic;
    rst_n : in std_logic;
    seconds : out std_logic_vector(5 downto 0);
    minutes : out std_logic_vector(5 downto 0);
    hours : out std_logic_vector(4 downto 0);
    dummy_port : out std_logic_vector(15 downto 0)
  );
  end component clock;

  component counter is
  generic(
    term_cnt : integer;
    inverted : boolean
  );
  port(
    clk : in std_logic;
    rst_n : in std_logic;
    count : out std_logic_vector(3 downto 0)
  );
  end component counter;

  -- clk_Rst
  signal clk : std_logic;
  signal rst : std_logic;
  -- clock
  signal seconds : std_logic_vector(5 downto 0);
  signal minutes : std_logic_vector(5 downto 0);
  signal hours : std_logic_vector(4 downto 0);
  signal dummy_port : std_logic_vector(15 downto 0);
  -- counter
  signal count : std_logic_vector(3 downto 0);

begin

  clk_Rst_0_i : clk_Rst
  generic map(
    clk_prd => open
  );
  port map(
    clk => clk,
    input_one => open,
    input_two => open,
    rst => rst,
    custom_signal => open
  );

  clock_0_i : clock
  port map(
    clk => open,
    rst_n => open,
    seconds => seconds,
    minutes => minutes,
    hours => hours,
    dummy_port => dummy_port
  );

  counter_0_i : counter
  generic map(
    term_cnt => open,
    inverted => open
  );
  port map(
    clk => open,
    rst_n => open,
    count => count
  );

end architecture;
