-- -=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=- --
--     Code generated by VGen by Christian Manuel    --
-- -=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=-=#=- --
library ieee;
use ieee.std_logic_1164.all;

entity top_level is
end entity top_level;

architecture top_level_arch of top_level is

  component clk_rst is
  port(
    clk : out std_logic;
    rst : out std_logic
  );
  end component clk_rst;

  component clock is
  port(
    clk : in std_logic;
    rst_n : in std_logic;
    seconds : out std_logic_vector(5 downto 0);
    minutes : out std_logic_vector(5 downto 0);
    hours : out std_logic_vector(4 downto 0);
    dummy_port : out std_logic_vector(15 downto 0)
  );
  end component clock;

  component counter is
  generic(
    term_cnt : integer;
    inverted : boolean
  );
  port(
    clk : in std_logic;
    rst_n : in std_logic;
    count : out std_logic_vector(3 downto 0)
  );
  end component counter;

  -- clk_rst
  signal clk : std_logic;
  signal rst : std_logic;
  -- clock
  signal seconds : std_logic_vector(5 downto 0);
  signal minutes : std_logic_vector(5 downto 0);
  signal hours : std_logic_vector(4 downto 0);
  signal dummy_port : std_logic_vector(15 downto 0);
  -- counter
  signal count : std_logic_vector(3 downto 0);

begin

  clk_rst_0_i : clk_rst
  port map(
    clk => clk,
    rst => rst
  );

  clock_0_i : clock
  port map(
    clk => open,
    rst_n => open,
    seconds => seconds,
    minutes => minutes,
    hours => hours,
    dummy_port => dummy_port
  );

  counter_0_i : counter
  generic map(
    term_cnt => open,
    inverted => open
  );
  port map(
    clk => open,
    rst_n => open,
    count => count
  );

end architecture;
