"""

"""

from VHDL import *
import os
class Testbench(Entity):
    def __init__(self, arg):
        str_item = ''
        entity_item = Entity('dummy')

        if type(arg) == type(str_item):
            super().__init__(arg)
            self.__testbench_name = 'tb_' + super().get_entity_name()
            self.__isDependent = False
        elif type(arg) == type(entity_item):
            super().__init__(arg.get_entity_name())
            self.__testbench_name = 'tb_' + arg.get_entity_name()
            self.__isDependent = True

        self.__isCodeBodyEmpty = True

    def get_entity_name(self):
        return self.__testbench_name

    def generate_code(self):
        super().generate_code(self.__testbench_name)

    """
        To be revised :
            This method is exclusively used for instances of 'Testbench' generated by
            passing an 'Entity' object during its instantiation
    """
    def quick_test(self, ):
        if self.__isDependent:
            print('can execute code')
        else:
            print('cannot execute code')
