"""

"""

from VHDL import *
import os
class Testbench(Entity):
    def __init__(self, entity):
    
        super().__init__(entity.get_entity_name())
        self.__testbench_name = 'tb_' + entity.get_entity_name()
        self.isEmpty = True
        self.isDependent = True

    def get_entity_name(self):
        return self.__testbench_name

    def generate_code(self):
        super().generate_code(self.__testbench_name)

    """
        This method is exclusively used for instances of 'Testbench' generated by
        passing an 'Entity' object during its instantiation
    """
    def quick_test(self):
        pass
